<?php

namespace ex03Bundle\Repository;

/**
 * usertroisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usertroisRepository extends \Doctrine\ORM\EntityRepository
{
}
