<?php

namespace ex05Bundle\Repository;

/**
 * usercinqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usercinqRepository extends \Doctrine\ORM\EntityRepository
{
}
