d07:
    resource: "@D07Bundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

ex02:
  path:     /{_locale}/ex02/{count}
  defaults:  { _controller: D07Bundle:Ex02:translations, count: 0 }